name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout GitHub
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build
      run: |
        echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
        npm run build

    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: web-ext-artifacts/*.zip
        tag_name: v${{ env.VERSION }}
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}